version: "3.8"

services:
  ollama:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: ollama
    image: ollama/ollama
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/bash -c 'cat < /dev/null > /dev/tcp/localhost/11434 || exit 1'"]
      interval: 10s
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: on-failure
